/**
 * Tests for scripts/check-migration-compat.sh — the PR-time gate that
 * catches backward-incompatible migration DDL (issue #265 DoD).
 *
 * Runs the real script against temp fixtures and asserts exit codes, so the
 * BLOCK/WARN tiers are exercised end-to-end rather than mirrored.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT = fileURLToPath(
  new URL("../check-migration-compat.sh", import.meta.url),
);
const TMP = mkdtempSync(join(tmpdir(), "migration-compat-"));

function runScan(files) {
  try {
    const stdout = execFileSync("bash", [SCRIPT, ...files], {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    return { code: 0, output: stdout };
  } catch (err) {
    return { code: err.status ?? 1, output: `${err.stdout ?? ""}${err.stderr ?? ""}` };
  }
}

function fixture(name, sql) {
  const dir = join(TMP, name);
  mkdirSync(dir, { recursive: true });
  const file = join(dir, "migration.sql");
  writeFileSync(file, sql, "utf8");
  return file;
}

const LOCK = join(TMP, "migration_lock.toml");
writeFileSync(LOCK, '# Please do not edit this file manually\nprovider = "postgresql"\n', "utf8");

afterAll(() => {
  rmSync(TMP, { recursive: true, force: true });
});

describe("check-migration-compat.sh", () => {
  it("passes an additive (expand-phase) migration", () => {
    const file = fixture(
      "expand",
      `CREATE TABLE "Stream" ("id" TEXT NOT NULL, CONSTRAINT "Stream_pkey" PRIMARY KEY ("id"));\n` +
        `ALTER TABLE "Trade" ADD COLUMN "streamId" TEXT;\n` +
        `CREATE INDEX "Trade_streamId_idx" ON "Trade"("streamId");\n`,
    );
    const { code, output } = runScan([file, "--lock-file", LOCK]);
    expect(code).toBe(0);
    expect(output).toContain("No backward-incompatible");
  });

  it("blocks DROP TABLE", () => {
    const file = fixture("drop-table", `DROP TABLE "LegacyLedger";\n`);
    const { code, output } = runScan([file, "--lock-file", LOCK]);
    expect(code).toBe(1);
    expect(output).toContain("BLOCK");
    expect(output).toContain("DROP TABLE");
  });

  it("blocks a column rename", () => {
    const file = fixture("rename", `ALTER TABLE "Trade" RENAME COLUMN "oldId" TO "tradeId";\n`);
    const { code } = runScan([file, "--lock-file", LOCK]);
    expect(code).toBe(1);
  });

  it("blocks SET NOT NULL without expand/backfill", () => {
    const file = fixture("not-null", `ALTER TABLE "User" ALTER COLUMN "wallet" SET NOT NULL;\n`);
    const { code } = runScan([file, "--lock-file", LOCK]);
    expect(code).toBe(1);
  });

  it("blocks a column type change", () => {
    const file = fixture(
      "type-change",
      `ALTER TABLE "Trade" ALTER COLUMN "amount" TYPE NUMERIC(20,0) USING "amount"::NUMERIC;\n`,
    );
    const { code } = runScan([file, "--lock-file", LOCK]);
    expect(code).toBe(1);
  });

  it("warns (exit 0) on unique constraints — annotation tier only", () => {
    const file = fixture(
      "unique",
      `CREATE UNIQUE INDEX "Trade_ref_key" ON "Trade"("externalRef");\n`,
    );
    const { code, output } = runScan([file, "--lock-file", LOCK]);
    expect(code).toBe(0);
    expect(output).toContain("WARN");
  });

  it("fails when migration_lock.toml is missing", () => {
    const file = fixture("no-lock-ok", `CREATE TABLE "A" ("id" TEXT);\n`);
    const { code } = runScan([file, "--lock-file", join(TMP, "missing.toml")]);
    expect(code).toBe(1);
  });

  it("exits 0 when there is nothing to scan", () => {
    const { code } = runScan([]);
    expect(code).toBe(0);
  });
});
